export enum BoatCondition {
  NEW = 'NEW',
  USED = 'USED',
  REFURBISHED = 'REFURBISHED',
  DAMAGED = 'DAMAGED',
}

export enum BoatFuelType {
  GASOLINE = 'GASOLINE',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
  OTHER = 'OTHER',
}

export enum BoatClass {
  SAILBOAT = 'SAILBOAT',
  MOTORBOAT = 'MOTORBOAT',
  YACHT = 'YACHT',
  FISHING = 'FISHING',
  PONTOON = 'PONTOON',
  SPEEDBOAT = 'SPEEDBOAT',
  CATAMARAN = 'CATAMARAN',
  OTHER = 'OTHER',
}

export enum BoatMaterial {
  FIBERGLASS = 'FIBERGLASS',
  ALUMINUM = 'ALUMINUM',
  WOOD = 'WOOD',
  STEEL = 'STEEL',
  CARBON_FIBER = 'CARBON_FIBER',
  PLASTIC = 'PLASTIC',
  OTHER = 'OTHER',
}

export enum BoatPropellerType {
  FIXED = 'FIXED',
  FOLDING = 'FOLDING',
  FEATHERING = 'FEATHERING',
  SURFACE_PIERCING = 'SURFACE_PIERCING',
  CONTROLLABLE_PITCH = 'CONTROLLABLE_PITCH',
  OTHER = 'OTHER',
}
